<?php
    $this->headTitle($this->translate('Widget Visibility'));
    $this->headScript()->appendFile($this->basePath() . '/sc-default/js/stratch.js');

?>

    <div class="row">
        <div class="col-lg-12">
            <div class="form-group content-helper">
                <a href="<?= $this->url('sc-admin/layout', ['theme' => $theme]) ?>" class="btn btn-default"><?= $this->translate('Lyout') ?></a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 col-lg-8">
            <div class=" editor-tabs">
                <ul class="nav nav-tabs">
                    <li><a href="<?= $this->url('sc-admin/widget/configure', ['id' => $widgetId]) ?>"><span class="glyphicon glyphicon-cog"></span><?= $this->translate('Configure') ?></a></li>
                    <?php if(isset($config['backend'])): ?>

                    <li><a href="<?= $this->url('sc-admin/widget/edit', ['id' => $widgetId]) ?>"><span class="glyphicon glyphicon-edit"></span><?= $this->translate('Edit') ?></a></li>
                    <?php endif ?>

                    <li class="active"><a href="<?= $this->url('sc-admin/widget/visibility', ['id' => $widgetId]) ?>"><span class="glyphicon glyphicon-list"></span><?= $this->translate('Visibility') ?></a></li>
                </ul>
            </div>
            <div class="widget-name-info">

            </div>
            <div class="content-scrollarea stratch">
                @todo
            </div>
        </div>
        <div class="col-md-4 col-lg-4 indent-xs-sm">
            <div class="panel-group accordion" id="accordion">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#searchOptions">
                                <?php echo $this->translate('Search options') ?>

                            </a>
                        </h4>
                    </div>
                    <div id="searchOptions" class="panel-collapse collapse in">
                        <div class="panel-body">
                            @todo
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
