<?php
    $this->headTitle($this->translate('Widget Visibility'));
    $this->headScript()->appendFile($this->basePath() . '/sc-default/js/stratch.js');

?>

    <form action="<?= $this->url('sc-admin/widget/visibility', ['widget_id' => $widget->getId()]) ?>" method="post">
        <div class="row">
            <div class="col-lg-12">
                <div class="form-group content-helper">
                    <button class="btn btn-primary" name="suboperation" value="save" type="submit"><?= $this->translate('Save') ?></button>
                    <a href="<?= $this->url('sc-admin/layout', ['theme' => $widget->getTheme()]) ?>" class="btn btn-default"><?= $this->translate('Lyout') ?></a>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8 col-lg-8">
                <div class=" editor-tabs">
                    <?php if ($list->getTotalPages() > 1): ?>

                    <div class="page-control pull-right">
                        <div class="btn-group">
                            <a href="<?= $this->url('sc-admin/widget/visibility', ['widget_id' => $widget->getId(), 'content_id' => $options->getContentId(), 'filter' => $options->getFilter(), 'page' => 1]) ?>" class="btn btn-default btn-sm" title="<?= $this->translate('Go to the first page') ?>">«</a>
                            <a href="<?= $this->url('sc-admin/widget/visibility', ['widget_id' => $widget->getId(), 'content_id' => $options->getContentId(), 'filter' => $options->getFilter(), 'page' => max($options->getPage() - 1, 1)]) ?>" class="btn btn-default btn-sm" title="<?= $this->translate('Go to the previous page') ?>">‹</a>
                        </div>
                        <div class="page-control-form">
                            <div class="page-control-group">
                                <span class="page-control-input">
                                    <input type="text" name="page" value="<?= $options->getPage() ?>" class="form-control input-sm" title="<?= $this->translate('Current page') ?>" />
                                </span>
                                <span class="page-control-count">
                                    <span><?= $this->translate('of') ?> <?= $list->getTotalPages() ?></span>
                                </span>
                                <span class="page-control-button">
                                    <button class="btn btn-default btn-sm" name="go" value="go" type="submit"><?= $this->translate('Go') ?></button>
                                </span>
                            </div>
                        </div>
                        <div class="btn-group">
                            <a href="<?= $this->url('sc-admin/widget/visibility', ['widget_id' => $widget->getId(), 'content_id' => $options->getContentId(), 'filter' => $options->getFilter(), 'page' => min($options->getPage() + 1, $list->getTotalPages())]) ?>" class="btn btn-default btn-sm" title="<?= $this->translate('Go to the next page') ?>">›</a>
                            <a href="<?= $this->url('sc-admin/widget/visibility', ['widget_id' => $widget->getId(), 'content_id' => $options->getContentId(), 'filter' => $options->getFilter(), 'page' => $list->getTotalPages()]) ?>" class="btn btn-default btn-sm" title="<?= $this->translate('Go to the last page') ?>">»</a>
                        </div>
                    </div>
                    <?php endif ?>

                    <ul class="nav nav-tabs">
                        <li><a href="<?= $this->url('sc-admin/widget/configure', ['id' => $widget->getId()]) ?>"><span class="glyphicon glyphicon-cog"></span><?= $this->translate('Configure') ?></a></li>
                        <?php if (isset($config['backend'])): ?>

                        <li><a href="<?= $this->url('sc-admin/widget/edit', ['id' => $widget->getId()]) ?>"><span class="glyphicon glyphicon-edit"></span><?= $this->translate('Edit') ?></a></li>
                        <?php endif ?>

                        <li class="active"><a href="<?= $this->url('sc-admin/widget/visibility', ['widget_id' => $widget->getId()]) ?>"><span class="glyphicon glyphicon-list"></span><?= $this->translate('Visibility') ?></a></li>
                    </ul>
                </div>
                <div class="widget-display-name">
                    <h3 class="widget-display-name"><?= $widget->getDisplayName() ?></h3>
                </div>
                <div class="content-filters">
                    <div class="editor-pills inline-pills">
                        <ul class="nav nav-pills">
                            <li<?php if ($options->getFilter() == 'all'): ?> class="active"<?php endif ?>><a href="<?= $this->url('sc-admin/widget/visibility', ['widget_id' => $widget->getId(), 'content_id' => $options->getContentId(), 'filter' => 'all']) ?>"><?= $this->translate('All') ?> <span class="content-filters-count">(<?= $list->getCounter('all') ?>)</span></a></li>
                            <li<?php if ($options->getFilter() == 'categories'): ?> class="active"<?php endif ?>><a href="<?= $this->url('sc-admin/widget/visibility', ['widget_id' => $widget->getId(), 'content_id' => $options->getContentId(), 'filter' => 'categories']) ?>"><?= $this->translate('Categories') ?> <span class="content-filters-count">(<?= $list->getCounter('categories') ?>)</span></a></li>
                            <li<?php if ($options->getFilter() == 'articles'): ?> class="active"<?php endif ?>><a href="<?= $this->url('sc-admin/widget/visibility', ['widget_id' => $widget->getId(), 'content_id' => $options->getContentId(), 'filter' => 'articles']) ?>"><?= $this->translate('Articles') ?> <span class="content-filters-count">(<?= $list->getCounter('articles') ?>)</span></a></li>
                            <li<?php if ($options->getFilter() == 'files'): ?> class="active"<?php endif ?>><a href="<?= $this->url('sc-admin/widget/visibility', ['widget_id' => $widget->getId(), 'content_id' => $options->getContentId(), 'filter' => 'files']) ?>"><?= $this->translate('Files') ?> <span class="content-filters-count">(<?= $list->getCounter('files') ?>)</span></a></li>
                        </ul>
                    </div>
                     <?php if ($list->hasTop()): ?>

                    <div class="btn-group pull-right-gte-sm">
                        <button type="button" class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown"><?= $this->translate('Back to')?> <span class="caret"></span></button>
                        <ul class="dropdown-menu text-right-gte-sm back-menu" role="menu">
                            <?php foreach ($list->getBack() as $back): ?>

                            <li><a href="<?= $this->url('sc-admin/widget/visibility', ['widget_id' => $widget->getId(), 'content_id' => $back['id']]) ?>"><?= $this->translate($back['title']) ?></a></li>
                            <?php endforeach ?>

                        </ul>
                    </div>
                    <div class="clearfix"></div>
                    <?php endif ?>

                </div>
                <div class="content-root">/ <?= $this->translate($list->getParent('title')) ?></div>
                <div class="content-scrollarea stratch">
                    <table class="table table-hover table-condensed content-list">
                        <thead>
                            <tr>
                                <th class="content-list-icon hidden-xs">&nbsp;</th>
                                <th class="content-list-title"><a href="<?= $this->url('sc-admin/widget/visibility', ['widget_id' => $widget->getId(), 'content_id' => $list->getParent('id'), 'filter' => $options->getFilter(), 'page' => $options->getPage(), 'order_by' => 'title']) ?>"><?= $this->translate('Title') ?><?php if ($options->getOrderBy() == 'title'): ?><span class="caret-order-<?= $options->getOrder() ?>"></span><?php endif ?></a></th>
                                <th class="content-list-user hidden-xs"><a href="<?= $this->url('sc-admin/widget/visibility', ['widget_id' => $widget->getId(), 'content_id' => $list->getParent('id'), 'filter' => $options->getFilter(), 'page' => $options->getPage(), 'order_by' => 'user']) ?>"><?= $this->translate('Author') ?><?php if ($options->getOrderBy() == 'user'): ?><span class="caret-order-<?= $options->getOrder() ?>"></span><?php endif ?></a></th>
                                <th class="content-list-date hidden-xs"><a href="<?= $this->url('sc-admin/widget/visibility', ['widget_id' => $widget->getId(), 'content_id' => $list->getParent('id'), 'filter' => $options->getFilter(), 'page' => $options->getPage(), 'order_by' => 'date']) ?>"><?= $this->translate('Created') ?><?php if ($options->getOrderBy() == 'date'): ?><span class="caret-order-<?= $options->getOrder() ?>"></span><?php endif ?></a></th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th class="content-list-icon hidden-xs">&nbsp;</th>
                                <th class="content-list-title"><a href="<?= $this->url('sc-admin/widget/visibility', ['widget_id' => $widget->getId(), 'content_id' => $list->getParent('id'), 'filter' => $options->getFilter(), 'page' => $options->getPage(), 'order_by' => 'title']) ?>"><?= $this->translate('Title') ?><?php if ($options->getOrderBy() == 'title'): ?><span class="caret-order-<?= $options->getOrder() ?>"></span><?php endif ?></a></th>
                                <th class="content-list-user hidden-xs"><a href="<?= $this->url('sc-admin/widget/visibility', ['widget_id' => $widget->getId(), 'content_id' => $list->getParent('id'), 'filter' => $options->getFilter(), 'page' => $options->getPage(), 'order_by' => 'user']) ?>"><?= $this->translate('Author') ?><?php if ($options->getOrderBy() == 'user'): ?><span class="caret-order-<?= $options->getOrder() ?>"></span><?php endif ?></a></th>
                                <th class="content-list-date hidden-xs"><a href="<?= $this->url('sc-admin/widget/visibility', ['widget_id' => $widget->getId(), 'content_id' => $list->getParent('id'), 'filter' => $options->getFilter(), 'page' => $options->getPage(), 'order_by' => 'date']) ?>"><?= $this->translate('Created') ?><?php if ($options->getOrderBy() == 'date'): ?><span class="caret-order-<?= $options->getOrder() ?>"></span><?php endif ?></a></th>
                            </tr>
                        </tfoot>
                        <tbody>
                            <?php if ($list->hasTop()): ?>

                            <tr class="hidden-xs">
                                <td colspan="4" class="content-list-top">
                                    <a href="<?= $this->url('sc-admin/widget/visibility', ['widget_id' => $widget->getId(), 'content_id' => $list->getTop()]) ?>" class="content-list-top" title="<?= $this->translate('Go top') ?>"><span class="glyphicon glyphicon-chevron-up"></span> ...</a>
                                </td>
                            </tr>
                            <tr class="visible-xs">
                                <td class="content-list-top">
                                    <a href="<?= $this->url('sc-admin/widget/visibility', ['widget_id' => $widget->getId(), 'content_id' => $list->getTop()]) ?>" class="content-list-top" title="<?= $this->translate('Go top') ?>"><span class="glyphicon glyphicon-chevron-up"></span> ...</a>
                                </td>
                            </tr>
                            <?php endif ?>
                            <?php if ($list->isEmpty()): ?>

                            <tr class="hidden-xs">
                                <td colspan="4">
                                    <div class="well"><?= $this->translate('Nothing was found.') ?><?php if ('all' != $options->getFilter() && 0 < $list->getCounter('all')): ?> <?= $this->translate('Try to change the filter.') ?><?php endif ?></div>
                                </td>
                            </tr>
                            <tr class="visible-xs">
                                <td>
                                    <div class="well"><?= $this->translate('Nothing was found.') ?><?php if ('all' != $options->getFilter() && 0 < $list->getCounter('all')): ?> <?= $this->translate('Try to change the filter.') ?><?php endif ?></div>
                                </td>
                            </tr>
                            <?php endif ?>
                            <?php foreach ($list as $item): ?>

                            <tr>
                                <td class="content-list-icon hidden-xs">
                                    <?= $this->scContentFormat()->getIconPath($item) ?>

                                </td>
                                <td class="content-list-title">
                                    <?php if ($this->scContentFormat()->canPreview($item)): ?>

                                    <div class="content-item-actions widget-visibility-options pull-right">
                                        <div class="radio">
                                            <label>
                                                <input type="radio" name="state[<?= $item->getId() ?>]" value="1"<?php if(1 === $item->isEnabled()): ?> checked="checked"<?php endif ?>> <?= $this->translate('Enabled') ?>

                                            </label>
                                        </div>
                                        <div class="radio">
                                            <label>
                                                <input type="radio" name="state[<?= $item->getId() ?>]" value="0"<?php if(0 === $item->isEnabled()): ?> checked="checked"<?php endif ?>> <?= $this->translate('Disabled') ?>

                                            </label>
                                        </div>
                                        <div class="radio">
                                            <label>
                                                <input type="radio" name="state[<?= $item->getId() ?>]" value="-1"<?php if(-1 === $item->isEnabled()): ?> checked="checked"<?php endif ?>> <?= $this->translate('Inherit') ?>

                                            </label>
                                        </div>
                                        <input type="hidden" name="old_state[<?= $item->getId() ?>]" value="<?= $item->isEnabled() ?>" />
                                    </div>
                                    <?php endif ?>

                                    <span><?= $item->getTitle() ?></span>
                                    <br />
                                    <?php if ('file' != $item->getType()): ?>

                                    <span class="content-childrens">(<?= $item->getChildrens() ?>)</span>

                                    <?php else: ?>

                                    <span class="content-type"><?= $this->scContentFormat()->getExtension($item) ?></span>
                                    <?php endif ?>

                                    <br />
                                    <span class="content-item-actions">
                                        <?php if ('file' != $item->getType()): ?>
                                            <?php if ($options->getSearch()): ?>

                                            <a href="<?= $this->url('sc-admin/widget/visibility', ['widget_id' => $widget->getId(), 'content_id' => $item->getId()], ['query' => ['search' => '']]) ?>"><?= $this->translate('Use') ?></a>
                                            <?php else: ?>

                                            <a href="<?= $this->url('sc-admin/widget/visibility', ['widget_id' => $widget->getId(), 'content_id' => $item->getId()]) ?>"><?= $this->translate('Use') ?></a>

                                            <?php endif ?>
                                        <?php endif ?>
                                        <?php if ($this->scContentFormat()->canPreview($item)): ?>

                                            <?php if('file' != $item->getType()): ?>|&nbsp;<?php endif ?><a href="<?= $this->url('home', ['content-name' => $item->getName()]) ?>" target="blank"><?= $this->translate('Preview') ?></a>
                                        <?php endif ?>

                                    </span>
                                </td>
                                <td class="content-list-user hidden-xs">
                                    <span><?= $item->getUserName() ?></span><br /><span class="content-list-email"><?= $item->getUserEmail() ?></span>
                                </td>
                                <td class="content-list-date hidden-xs">
                                    <?= $this->scDateTime()->getDate($item->getDate()) ?><br />
                                    <?= $this->scDateTime()->getTime($item->getDate()) ?>

                                </td>
                            </tr>
                            <?php endforeach ?>

                        </tbody>
                    </table>
                </div>
            </div>
            <div class="col-md-4 col-lg-4 indent-xs-sm">
                <div class="panel-group accordion" id="accordion">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title">
                                <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#widget-visibility-search">
                                    <?php echo $this->translate('Search') ?>

                                </a>
                            </h4>
                        </div>
                        <div id="widget-visibility-search" class="panel-collapse collapse in">
                            <div class="panel-body">
                                <label for="search"><?= $this->translate('Containing Text') ?></label>
                                <input class="form-control" type="text" id="search" name="search" value="<?= $options->getSearch() ?>" />
                                <p class="help-block"><?= $this->translate('A word or a few words separated by a space.') ?></p>
                                <div class="radio">
                                    <label>
                                        <input type="radio" name="search_source" value="title"<?php if('title' === $options->getSearchSource()): ?> checked="checked"<?php endif ?>> <?= $this->translate('In the title') ?>

                                    </label>
                                </div>
                                <div class="radio">
                                    <label>
                                        <input type="radio" name="search_source" value="name"<?php if('name' === $options->getSearchSource()): ?> checked="checked"<?php endif ?>> <?= $this->translate('In the name') ?>

                                    </label>
                                </div>
                                <div class="radio">
                                    <label>
                                        <input type="radio" name="search_source" value="content"<?php if('content' === $options->getSearchSource()): ?> checked="checked"<?php endif ?>> <?= $this->translate('In the content') ?>

                                    </label>
                                </div>
                                <div class="radio">
                                    <label>
                                        <input type="radio" name="search_source" value="description"<?php if('description' === $options->getSearchSource()): ?> checked="checked"<?php endif ?>> <?= $this->translate('In the description') ?>

                                    </label>
                                </div>
                                <button class="btn btn-default" value="save" type="submit"><?= $this->translate('Search') ?></button>
                                <button class="btn btn-default" name="search" value="" type="submit"><?= $this->translate('Clean') ?></button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
