<?php
    $this->headTitle($this->translate('Edit Category'));
    $this->headScript()->appendFile($this->basePath() . '/sc-default/tinymce/tinymce.min.js');
?>
<?php
    $form->prepare();
    echo $this->form()->openTag($form);
?>

    <div class="row">
        <div class="col-md-12 col-lg-12">
            <div class="form-group content-helper">
                <?= $this->formButton($form->get('save')) ?>

                <a href="<?= $this->url('sc-admin/content-manager') ?>" class="btn btn-default"><?= $this->translate('Manager') ?></a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-8 col-md-8 col-lg-8">
            <div class="form-group">
                <span><?= $this->translate('Permalink:') ?></span>
                <a href="<?= $this->url('sc', ['content-name' => $content->getName()]) ?>" target="blank"><?= $this->url('sc', ['content-name' => $content->getName()], ['force_canonical' => true]) ?></a>
            </div>
            <div class="form-group">
                <?= $this->formText($form->get('title')) ?>
                <?php if(count($form->get('title')->getMessages())): ?>

                <div class="alert alert-warning"><?= $this->formElementErrors($form->get('title')) ?></div>

                <?php endif ?>

            </div>
            <div class="form-group">
                <?= $this->formRow($form->get('description')) ?>

            </div>
        </div>
        <div class="col-sm-4 col-md-4 col-lg-4">
            <div class="panel-group accordion" id="accordion">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseOptions">
                                <?= $this->translate('Category options') ?>

                            </a>
                        </h4>
                    </div>
                    <div id="collapseOptions" class="panel-collapse collapse in">
                        <div class="panel-body">
                            <div class="form-group">
                                <?= $this->formLabel($form->get('status')) ?>

                                <?= $this->formSelect($form->get('status')) ?>

                                <?php if(count($form->get('status')->getMessages())): ?>

                                <div class="alert alert-warning"><?= $this->formElementErrors($form->get('status')) ?></div>

                                <?php endif ?>

                            </div>
                            <div class="form-group">
                                <?= $this->formlabel($form->get('name')) ?>

                                <?= $this->formText($form->get('name')) ?>
                                <?php if(count($form->get('name')->getMessages())): ?>

                                <div class="alert alert-warning"><?= $this->formElementErrors($form->get('name')) ?></div>

                                <?php endif ?>

                            </div>

                            <?= $this->partial('sc-default/template/backend/partial/content-info.phtml', array(
                                'content' => $content,
                                'meta' => $content->getInfo(),
                            )) ?>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

<?= $this->form()->closeTag($form) ?>

<?php
$tinyMceStyles = $this->basePath() . '/sc-default/css/tinymce.css';
$language = $this->scLocalization()->getPrimaryLanguage();
$baseUrl = $this->url('sc', [], ['force_canonical' => true]);
echo $this->inlineScript()->appendScript(<<<EOT
    tinymce.init({
        language: "$language",
        document_base_url: "$baseUrl",
        relative_urls: true,
        selector: "textarea#description",
        theme: "modern",
        plugins: [
             "advlist autolink link image lists charmap print preview hr anchor pagebreak spellchecker",
             "searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking",
             "save table contextmenu directionality emoticons template paste textcolor"
       ],
       content_css: "$tinyMceStyles",
       toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | l      ink image | print preview media fullpage | forecolor backcolor emoticons",
    });
EOT
); ?>
