<?php
    $this->headTitle($this->translate('Content Manager'));
    $this->headScript()->appendFile($this->basePath() . '/sc-default/js/content-manager.js')
                       ->appendFile($this->basePath() . '/sc-default/js/stratch.js');
?>
<?php if (isset($messages)): ?>

    <?php echo $this->partial('sc-default/template/backend/partial/error.phtml') ?>
<?php endif ?>

<div class="row">
    <?php echo $this->partial('sc-default/template/backend/content-manager/pane.phtml', array(
        'otherType' => $optionsProvider->getOtherOptions('first')->getType(),
        'otherRoot' => $optionsProvider->getOtherOptions('first')->getRoot(),
        'options' => $optionsProvider->getOptions('first'),
        'list' => $contentListsProvider->getList('first'),
        'pane' => 'first',
    )) ?>

    <?php echo $this->partial('sc-default/template/backend/content-manager/pane.phtml', array(
        'otherType' => $optionsProvider->getOtherOptions('second')->getType(),
        'otherRoot' => $optionsProvider->getOtherOptions('second')->getRoot(),
        'options' => $optionsProvider->getOptions('second'),
        'list' => $contentListsProvider->getList('second'),
        'pane' => 'second',
    )) ?>

</div>
