<div class="col-md-6 col-lg-6 pane-<?php echo $pane ?>">
    <form action="<?php echo $this->url('sc-admin/content-manager') ?>" method="post">
        <input type="hidden" name="pane" value="<?php echo $options->getName() ?>">
        <div class="editor-tabs">
            <?php if($list->getTotalPages() > 1): ?>
            
            <div class="page-control pull-right">
                <div class="btn-group">
                    <a href="<?php echo $this->url('sc-admin/content-manager', array('pane' => $pane, 'type' => $options->getType(), 'root' => $options->getRoot(), 'filter' => $options->getFilter(), 'parent' => $options->getParent(), 'page' => 1)) ?>" class="btn btn-default btn-sm" title="<?php echo $this->translate('Go to the first page') ?>">«</a>
                    <a href="<?php echo $this->url('sc-admin/content-manager', array('pane' => $pane, 'type' => $options->getType(), 'root' => $options->getRoot(), 'filter' => $options->getFilter(), 'parent' => $options->getParent(), 'page' => max($options->getPage() - 1, 1))) ?>" class="btn btn-default btn-sm" title="<?php echo $this->translate('Go to the previous page') ?>">‹</a>
                </div>
                <div class="page-control-form">
                    <div class="page-control-group">
                        <span class="page-control-input">
                            <input type="text" name="page" value="<?php echo $options->getPage() ?>" class="form-control input-sm" title="<?php echo $this->translate('Current page') ?>" />
                        </span>
                        <span class="page-control-count">
                            <span><?php echo $this->translate('of') ?> <?php echo $list->getTotalPages() ?></span>
                        </span>
                        <span class="page-control-button">
                            <button class="btn btn-default btn-sm" name="suboperation" value="gotopage" type="submit"><?php echo $this->translate('Go') ?></button>
                        </span>
                    </div>
                </div>
                <div class="btn-group">
                    <a href="<?php echo $this->url('sc-admin/content-manager', array('pane' => $pane, 'type' => $options->getType(), 'root' => $options->getRoot(), 'filter' => $options->getFilter(), 'parent' => $options->getParent(), 'page' => min($options->getPage() + 1, $list->getTotalPages()))) ?>" class="btn btn-default btn-sm" title="<?php echo $this->translate('Go to the next page') ?>">›</a>
                    <a href="<?php echo $this->url('sc-admin/content-manager', array('pane' => $pane, 'type' => $options->getType(), 'root' => $options->getRoot(), 'filter' => $options->getFilter(), 'parent' => $options->getParent(), 'page' => $list->getTotalPages())) ?>" class="btn btn-default btn-sm" title="<?php echo $this->translate('Go to the last page') ?>">»</a>
                </div>
            </div>
            <?php endif ?>
            
            <ul class="nav nav-tabs">
                <li<?php if($options->getType() == 'list' && $options->getRoot() == 'site'): ?> class="active"<?php endif ?>><a href="<?php echo $this->url('sc-admin/content-manager', array('pane' => $pane, 'type' => 'list', 'root' => 'site')) ?>"><span class="glyphicon glyphicon-globe"></span><?php echo $this->translate('Web Site') ?></a></li>
                <li<?php if($options->getType() == 'list' && $options->getRoot() == 'trash'): ?> class="active"<?php endif ?>><a href="<?php echo $this->url('sc-admin/content-manager', array('pane' => $pane, 'type' => 'list', 'root' => 'trash')) ?>"><span class="glyphicon glyphicon-trash"></span><?php echo $this->translate('Trash') ?></a></li>
                <li<?php if($options->getType() == 'search'): ?> class="active"<?php endif ?>><a href="<?php echo $this->url('sc-admin/content-manager', array('pane' => $pane, 'type' => 'search')) ?>"><span class="glyphicon glyphicon-search"></span><?php echo $this->translate('Search') ?></a></li>
            </ul>
        </div>
        <div class="content-filters editor-pills">
            <ul class="nav nav-pills">
                <li<?php if($options->getFilter() == 'all'): ?> class="active"<?php endif ?>><a href="<?php echo $this->url('sc-admin/content-manager', array('pane' => $pane, 'type' => $options->getType(), 'root' => $options->getRoot(), 'filter' => 'all')) ?>"><?php echo $this->translate('All') ?> <span class="content-filters-count">(<?php echo $list->getCounter('all') ?>)</span></a></li>
                <li<?php if($options->getFilter() == 'categories'): ?> class="active"<?php endif ?>><a href="<?php echo $this->url('sc-admin/content-manager', array('pane' => $pane, 'type' => $options->getType(), 'root' => $options->getRoot(), 'filter' => 'categories')) ?>"><?php echo $this->translate('Categories') ?> <span class="content-filters-count">(<?php echo $list->getCounter('categories') ?>)</span></a></li>
                <li<?php if($options->getFilter() == 'articles'): ?> class="active"<?php endif ?>><a href="<?php echo $this->url('sc-admin/content-manager', array('pane' => $pane, 'type' => $options->getType(), 'root' => $options->getRoot(), 'filter' => 'articles')) ?>"><?php echo $this->translate('Articles') ?> <span class="content-filters-count">(<?php echo $list->getCounter('articles') ?>)</span></a></li>
                <li<?php if($options->getFilter() == 'files'): ?> class="active"<?php endif ?>><a href="<?php echo $this->url('sc-admin/content-manager', array('pane' => $pane, 'type' => $options->getType(), 'root' => $options->getRoot(), 'filter' => 'files')) ?>"><?php echo $this->translate('Files') ?> <span class="content-filters-count">(<?php echo $list->getCounter('files') ?>)</span></a></li>
            </ul>
        </div>
        <div class="content-actions">
            <div class="btn-group btn-group-sm">
                <?php if($options->getRoot() == 'trash'): ?>
                    <?php if($otherType == 'list' && $otherRoot == 'site'): ?>
                    <button class="btn btn-default btn-sm" name="suboperation" value="recovery" type="submit"><?php echo $this->translate('Recovery') ?></button>
                    <?php endif ?>
                    
                    <button class="btn btn-default btn-sm" name="suboperation" value="delete" type="submit" onclick="return confirm('<?php echo $this->translate('Are you sure, you want to delete the contents?') ?>') ? true : false;"><?php echo $this->translate('Delete') ?></button>
                    <?php if($options->getType() == 'list'): ?>
                    
                    <button class="btn btn-default btn-sm" name="suboperation" value="clean" type="submit" onclick="return confirm('<?php echo $this->translate('Are you sure, you want to empty trash?') ?>') ? true : false;"><?php echo $this->translate('Empty Trash') ?></button>
                    <?php endif ?>
                <?php endif ?>
                <?php if($options->getRoot() == 'site'): ?>
                    <?php if($options->getType() == 'list'): ?>
                    
                    <button class="btn btn-default btn-sm" name="suboperation" value="reorder" type="submit" <?php if($options->getOrderBy() != 'natural' || $options->getFilter() != 'all'): ?> disabled="disabled" <?php endif ?>><?php echo $this->translate('Reorder') ?></button>
                    <?php endif ?>
                    <?php if($otherType == 'list' && $otherRoot == 'site'): ?>
                    
                    <button class="btn btn-default btn-sm" name="suboperation" value="move" type="submit"><?php echo $this->translate('Move') ?></button>
                    <?php endif ?>
                
                    <button class="btn btn-default btn-sm" name="suboperation" value="trash" type="submit"><?php echo $this->translate('Move to Trash') ?></button>
                    <?php if($options->getType() == 'list'): ?>
                    <button type="button" class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown"><?php echo $this->translate('Add') ?> <span class="caret"></span></button>
                    <ul class="dropdown-menu text-right" role="menu">
                      <li><a href="<?php echo $this->url('sc-admin/category/add', array('parent' => $options->getParent())) ?>"><?php echo $this->translate('Category') ?></a></li>
                      <li><a href="<?php echo $this->url('sc-admin/article/add', array('parent' => $options->getParent())) ?>"><?php echo $this->translate('Article') ?></a></li>
                      <li><a href="<?php echo $this->url('sc-admin/file/add', array('parent' => $options->getParent())) ?>"><?php echo $this->translate('File') ?></a></li>
                    </ul>
                    <?php endif ?>
                <?php endif ?>
                <?php if('search' == $options->getType()): ?>
                    
                    <a href="<?php echo $this->url('sc-admin/content-search', array('pane' => $pane)) ?>" class="btn btn-default btn-sm"><?php echo $this->translate('Search Preferences') ?></a>
                <?php endif ?>
                
            </div>
            
            <?php if($list->hasTop()): ?>
            <div class="btn-group pull-right">
                <button type="button" class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown"><?php echo $this->translate('Back to')?> <span class="caret"></span></button>
                <ul class="dropdown-menu text-right" role="menu">
                    <?php foreach($list->getBack() as $back): ?>
                                        
                    <li><a href="<?php echo $this->url('sc-admin/content-manager', array('pane' => $pane, 'type' => $options->getType(), 'root' => $options->getRoot(), 'filter' => $options->getFilter(), 'parent' => $back['id'])) ?>"><?php echo $this->translate($back['title']) ?></a></li>
                    <?php endforeach ?>
                    
                </ul>
            </div>
            <div class="clearfix"></div>
            <?php endif ?>
            
        </div>
        <div class="content-root">/ <?php echo $this->translate($list->getParent('title')) ?></div>
        <div class="content-scrollarea">
            <table class="table table-hover table-condensed content-list">
                <thead>
                    <tr>
                        <th class="content-list-check hide-if-no-js"><input type="checkbox"<?php if($list->isEmpty()): ?> disabled="disabled"<?php endif ?> /></th>
                        <th class="content-list-icon hidden-xs">&nbsp;</th>
                        <th class="content-list-order"><a href="<?php echo $this->url('sc-admin/content-manager', array('pane' => $pane, 'type' => $options->getType(), 'root' => $options->getRoot(), 'filter' => $options->getFilter(), 'parent' => $options->getParent(), 'page' => $options->getPage(), 'order_by' => 'natural')) ?>">№<?php if($options->getOrderBy() == 'natural'): ?><span class="caret-order-<?php echo $options->getOrder() ?>"></span><?php endif ?></a></th>
                        <th class="content-list-title"><a href="<?php echo $this->url('sc-admin/content-manager', array('pane' => $pane, 'type' => $options->getType(), 'root' => $options->getRoot(), 'filter' => $options->getFilter(), 'parent' => $options->getParent(), 'page' => $options->getPage(), 'order_by' => 'title')) ?>"><?php echo $this->translate('Title') ?><?php if($options->getOrderBy() == 'title'): ?><span class="caret-order-<?php echo $options->getOrder() ?>"></span><?php endif ?></a></th>
                        <th class="content-list-status hidden-xs"><a href="<?php echo $this->url('sc-admin/content-manager', array('pane' => $pane, 'type' => $options->getType(), 'root' => $options->getRoot(), 'filter' => $options->getFilter(), 'parent' => $options->getParent(), 'page' => $options->getPage(), 'order_by' => 'status')) ?>"><?php echo $this->translate('St') ?><?php if($options->getOrderBy() == 'status'): ?><span class="caret-order-<?php echo $options->getOrder() ?>"></span><?php endif ?></a></th>
                        <th class="content-list-user hidden-xs"><a href="<?php echo $this->url('sc-admin/content-manager', array('pane' => $pane, 'type' => $options->getType(), 'root' => $options->getRoot(), 'filter' => $options->getFilter(), 'parent' => $options->getParent(), 'page' => $options->getPage(), 'order_by' => 'user')) ?>"><?php echo $this->translate(ucfirst($options->getUserType())) ?><?php if($options->getOrderBy() == 'user'): ?><span class="caret-order-<?php echo $options->getOrder() ?>"></span><?php endif ?></a></th>
                        <th class="content-list-date hidden-xs"><a href="<?php echo $this->url('sc-admin/content-manager', array('pane' => $pane, 'type' => $options->getType(), 'root' => $options->getRoot(), 'filter' => $options->getFilter(), 'parent' => $options->getParent(), 'page' => $options->getPage(), 'order_by' => 'date')) ?>"><?php echo $this->translate(ucfirst($options->getModificationType())) ?><?php if($options->getOrderBy() == 'date'): ?><span class="caret-order-<?php echo $options->getOrder() ?>"></span><?php endif ?></a></th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th class="content-list-check hide-if-no-js"><input type="checkbox"<?php if($list->isEmpty()): ?> disabled="disabled"<?php endif ?> /></th>
                        <th class="content-list-icon hidden-xs">&nbsp;</th>
                        <th class="content-list-order"><a href="<?php echo $this->url('sc-admin/content-manager', array('pane' => $pane, 'type' => $options->getType(), 'root' => $options->getRoot(), 'filter' => $options->getFilter(), 'parent' => $options->getParent(), 'page' => $options->getPage(), 'order_by' => 'natural')) ?>">№<?php if($options->getOrderBy() == 'natural'): ?><span class="caret-order-<?php echo $options->getOrder() ?>"></span><?php endif ?></a></th>
                        <th class="content-list-title"><a href="<?php echo $this->url('sc-admin/content-manager', array('pane' => $pane, 'type' => $options->getType(), 'root' => $options->getRoot(), 'filter' => $options->getFilter(), 'parent' => $options->getParent(), 'page' => $options->getPage(), 'order_by' => 'title')) ?>"><?php echo $this->translate('Title') ?><?php if($options->getOrderBy() == 'title'): ?><span class="caret-order-<?php echo $options->getOrder() ?>"></span><?php endif ?></a></th>
                        <th class="content-list-status hidden-xs"><a href="<?php echo $this->url('sc-admin/content-manager', array('pane' => $pane, 'type' => $options->getType(), 'root' => $options->getRoot(), 'filter' => $options->getFilter(), 'parent' => $options->getParent(), 'page' => $options->getPage(), 'order_by' => 'status')) ?>"><?php echo $this->translate('St') ?><?php if($options->getOrderBy() == 'status'): ?><span class="caret-order-<?php echo $options->getOrder() ?>"></span><?php endif ?></a></th>
                        <th class="content-list-user hidden-xs"><a href="<?php echo $this->url('sc-admin/content-manager', array('pane' => $pane, 'type' => $options->getType(), 'root' => $options->getRoot(), 'filter' => $options->getFilter(), 'parent' => $options->getParent(), 'page' => $options->getPage(), 'order_by' => 'user')) ?>"><?php echo $this->translate(ucfirst($options->getUserType())) ?><?php if($options->getOrderBy() == 'user'): ?><span class="caret-order-<?php echo $options->getOrder() ?>"></span><?php endif ?></a></th>
                        <th class="content-list-date hidden-xs"><a href="<?php echo $this->url('sc-admin/content-manager', array('pane' => $pane, 'type' => $options->getType(), 'root' => $options->getRoot(), 'filter' => $options->getFilter(), 'parent' => $options->getParent(), 'page' => $options->getPage(), 'order_by' => 'date')) ?>"><?php echo $this->translate(ucfirst($options->getModificationType())) ?><?php if($options->getOrderBy() == 'date'): ?><span class="caret-order-<?php echo $options->getOrder() ?>"></span><?php endif ?></a></th>
                    </tr>
                </tfoot>
                <tbody>
                    <?php if($list->hasTop()): ?>
                    
                    <tr class="hidden-xs">
                        <td colspan="7" class="content-list-top">
                            <a href="<?php echo $this->url('sc-admin/content-manager', array('pane' => $pane, 'type' => $options->getType(), 'root' => $options->getRoot(), 'filter' => $options->getFilter(), 'parent' => $list->getTop())) ?>" class="content-list-top" title="<?php echo $this->translate('Go top') ?>"><span class="glyphicon glyphicon-chevron-up"></span> ...</a>
                        </td>
                    </tr>
                    <tr class="visible-xs">
                        <td colspan="3" class="content-list-top">
                            <a href="<?php echo $this->url('sc-admin/content-manager', array('pane' => $pane, 'type' => $options->getType(), 'root' => $options->getRoot(), 'filter' => $options->getFilter(), 'parent' => $list->getTop())) ?>" class="content-list-top" title="<?php echo $this->translate('Go top') ?>"><span class="glyphicon glyphicon-chevron-up"></span> ...</a>
                        </td>
                    </tr>
                    <?php endif ?>
                    <?php if($list->isEmpty()): ?>
                    
                    <tr class="hidden-xs">
                        <td colspan="7">
                            <div class="well"><?php echo $this->translate('Nothing was found.') ?><?php if('all' != $options->getFilter() && 0 < $list->getCounter('all')): ?> <?php echo $this->translate('Try to change the filter.') ?><?php endif ?></div>
                        </td>
                    </tr>
                    <tr class="visible-xs">
                        <td colspan="3">
                            <div class="well"><?php echo $this->translate('Nothing was found.') ?><?php if('all' != $options->getFilter() && 0 < $list->getCounter('all')): ?> <?php echo $this->translate('Try to change the filter.') ?><?php endif ?></div>
                        </td>
                    </tr>
                    <?php endif ?>
                    <?php foreach($list as $item): ?>
                    
                    <tr>
                        <td class="content-list-check hide-if-no-js">
                            <input type="checkbox" name="id[]" value="<?php echo $item->getId() ?>" id="checkbox-<?php echo $pane ?>-<?php echo $item->getId() ?>" />
                        </td>
                        <td class="content-list-icon hidden-xs">
                            <label for="checkbox-<?php echo $pane ?>-<?php echo $item->getId() ?>"><?php echo $this->scContentFormat()->getIconPath($item) ?></label>
                        </td>
                        <td class="content-list-order">
                            <input class="form-control input-sm" type="text" name="position[<?php echo $item->getId() ?>]" value="<?php echo $item->getOrder() ?>"<?php if($options->getType() != 'list' || $options->getRoot() != 'site'|| $options->getFilter() != 'all' || $options->getOrderBy() != 'natural'): ?> disabled="disabled"<?php endif ?> />
                            <?php if($options->getType() == 'list' && $options->getRoot() == 'site' && $options->getFilter() == 'all' && $options->getOrderBy() == 'natural'): ?><input type="hidden" name="old_position[<?php echo $item->getId() ?>]" value="<?php echo $item->getOrder() ?>" /><?php endif ?>
                            
                        </td>
                        <td class="content-list-title">
                            <span><?php echo $item->getTitle() ?></span>
                            <br />
                            <?php if('file' != $item->getType()): ?>
                            
                            <span class="content-childrens">(<?php echo $item->getChildrens() ?>)</span>
                            
                            <?php else: ?>
                            
                            <span class="content-type"><?php echo $this->scContentFormat()->getExtension($item) ?></span>
                            <?php endif ?>
                            
                            <br />
                            <span class="content-item-actions">
                                <?php if('file' != $item->getType()): ?>
                                
                                <a href="<?php echo $this->url('sc-admin/content-manager', array('pane' => $pane, 'type' => 'list', 'root' => $options->getRoot(), 'filter' => $options->getFilter(), 'parent' => $item->getId())) ?>"><?php echo $this->translate('Use') ?></a>
                                <?php endif ?>
                                <?php if($options->getRoot() != 'trash'): ?>
                                
                                    <?php if('file' != $item->getType()): ?>|&nbsp;<?php endif ?><a href="<?php echo $this->url('sc-admin/' . $item->getType() . '/edit', array('id' => $item->getId())) ?>"><?php echo $this->translate('Edit') ?></a>
                                        <?php if($this->scContentFormat()->canPreview($item)): ?>
                                        
                                        |&nbsp;<a href=""><?php echo $this->translate('Preview') ?></a>
                                        <?php endif ?>
                                <?php endif ?>
                                
                            </span>
                        </td>
                        <td class="content-list-status hidden-xs">
                            <?php if('published' == $item->getStatus()): ?>
                            
                            <span class="glyphicon glyphicon-eye-open"></span>
                            <?php else: ?>
                            
                            <span class="glyphicon glyphicon-eye-close"></span>
                            <?php endif ?>
                            
                        </td>
                        <td class="content-list-user hidden-xs">
                            <span><?php echo $item->getUserName() ?></span><br /><span class="content-list-email"><?php echo $item->getUserEmail() ?></span>
                        </td>
                        <td class="content-list-date hidden-xs">
                            <?php echo $this->scDateTime()->getDate($item->getDate()) ?><br />
                            <?php echo $this->scDateTime()->getTime($item->getDate()) ?>
                            
                        </td>
                    </tr>
                    
                    <?php endforeach ?>
                    
                </tbody>
            </table>
        </div>
    </form>
</div>
