<?php echo $this->doctype(); ?>

<html lang="en">
<head>
<meta charset="utf-8">
<?php echo $this->headTitle('ScContent . ' . $this->translate('Administrator'), \Zend\View\Helper\Placeholder\Container\AbstractContainer::PREPEND)->setSeparator(' . ')->setAutoEscape(false) ?>
<?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')
                            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')

?>

<!-- Styles -->
<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/sc-default/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/sc-default/css/common.css')
                ->prependStylesheet($this->basePath() . '/sc-default/css/bootstrap-theme.min.css')
                ->prependStylesheet($this->basePath() . '/sc-default/css/bootstrap.min.css')
?>

<!-- Scripts -->
<?php echo $this->headScript()->prependFile($this->basePath() . '/sc-default/js/respond.min.js')
                              ->prependFile($this->basePath() . '/sc-default/js/bootstrap.min.js')
                              ->prependFile($this->basePath() . '/sc-default/js/jquery.min.js')
                              ->prependFile($this->basePath() . '/sc-default/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9'))
?>
    
</head>
<body>
<div id="wrap">
<div id="main">
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?php echo $this->url() ?>">ScContent</a>
        </div>
        <div class="collapse navbar-collapse navbar-ex1-collapse">
            <ul class="nav navbar-nav">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#"><?php echo $this->translate('Content') ?> <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="<?php echo $this->url('sc-admin/content-manager') ?>"><?php echo $this->translate('Manager') ?></a></li>
                        <li><a href="<?php echo $this->url('sc-admin/content-search') ?>"><?php echo $this->translate('Search') ?></a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#"><?php echo $this->translate('Appearance') ?> <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="<?php echo $this->url('sc-admin/themes') ?>"><?php echo $this->translate('Themes') ?></a></li>
                        <li><a href="<?php echo $this->url('sc-admin/layout') ?>"><?php echo $this->translate('Layout') ?></a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</div>
<div class="container">

    <?php echo $this->content ?>
    
</div>   
</div>
</div>
<footer id="footer">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <p id="copyright">&copy; 2013 ScContent &ndash; Thank you for using.</p>
            </div>
        </div>
    </div>
</footer>
</body>
</html>
