<?= $this->doctype(); ?>

<html dir="<?= $this->scLanguageDirection() ?>" lang="<?= \Locale::getPrimaryLanguage(\Locale::getDefault()) ?>">
<head>
<meta charset="utf-8">
<?= $this->headTitle(
        'ScContent . ' . $this->translate('Administrator'),
        \Zend\View\Helper\Placeholder\Container\AbstractContainer::PREPEND
    )
    ->setSeparator(' . ')
    ->setAutoEscape(false)
?>

<?= $this->headMeta()
    ->appendName('viewport', 'width=device-width, initial-scale=1.0')
    ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')

?>

<!-- Styles -->
<?= $this->headLink([
        'rel' => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath() . '/sc-default/img/favicon.ico']
    )
    ->prependStylesheet($this->basePath() . '/sc-default/css/backend.css')
    ->prependStylesheet($this->basePath() . '/sc-default/css/common.css')
    ->prependStylesheet($this->basePath() . '/sc-default/css/bootstrap-theme.min.css')
    ->prependStylesheet($this->basePath() . '/sc-default/css/bootstrap.min.css')
?>

<!-- Scripts -->
<?= $this->headScript()
    ->prependFile($this->basePath() . '/sc-default/js/respond.min.js')
    ->prependFile($this->basePath() . '/sc-default/js/bootstrap.min.js')
    ->prependFile($this->basePath() . '/sc-default/js/jquery.min.js')
    ->prependFile($this->basePath() . '/sc-default/js/html5.js', 'text/javascript', ['conditional' => 'lt IE 9'])
?>
<?php $this->headScript()->prependFile('/test.js')?>

</head>
<?= $this->scBodyTag('class', $this->scLanguageDirection()) ?>

<div id="wrap">
<div id="main">
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="nav-helper"><a href="<?= $this->url('zfcuser/logout') ?>"><span class="glyphicon glyphicon-log-out" title="<?= $this->translate('Sign Out') ?>"></span></a></div>
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?= $this->url('sc-admin/content-manager') ?>">
                <img class="sc-logo" src="<?= $this->basepath() . '/sc-default/img/logo.png' ?>" alt="ScContent" />
            </a>
        </div>
        <div class="collapse navbar-collapse navbar-ex1-collapse">
            <?= $this->navigation('ScNavigation.Backend')->menu()->setPartial(['sc-default/layout/backend/navigation', 'sc-backend']) ?>

        </div>
    </div>
</div>
<div class="container">

    <?= $this->content ?>

</div>
</div>
</div>
<footer id="footer">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <p class="pull-right sc-version">v - <?= SC_VERSION ?></p>
                <p id="copyright">&copy; 2013 ScContent &ndash; Thank you for using.</p>
            </div>
        </div>
    </div>
</footer>
<?= $this->scBodyTag() ?>

</html>
