
            <ul class="nav navbar-nav">
            <?php foreach($this->container as $page): ?>
                <?php if (! $page->isVisible() || !$this->navigation()->accept($page)) continue ?>
                <?php if (! $page->hasPages()): ?>

                <li><a href="<?php echo $page->getHref() ?>"><?= $this->translate($page->getLabel()) ?></a></li>

                <?php else: ?>

                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="<?= $page->getHref() ?>">
                        <?= $this->translate($page->getLabel()) ?> <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                    <?php foreach($page->getPages() as $child): ?>
                        <?php if (! $child->isVisible() || !$this->navigation()->accept($child)) continue ?>

                        <li><a href="<?= $child->getHref() ?>"><?= $this->translate($child->getLabel()) ?></a></li>
                    <?php endforeach ?>

                    </ul>
                </li>
                <?php endif ?>
            <?php endforeach ?>

            </ul>
