<?php
    $this->headTitle($this->translate('Themes'));
?>
<?php if (isset($messages)): ?>

    <?= $this->partial('sc-default/template/backend/partial/error.phtml') ?>

<?php endif ?>
<?php foreach($options->getThemes() as $name => $item): ?>
<?php $displayName = isset($item['display_name']) ? $item['display_name'] : $name ?>

    <div class="row theme-row">
        <div class="col-lg-12">
            <div class="theme-item">
                <?php if (isset($item['screenshot'])): ?>

                <img class="theme-screenshot" src="<?= $this->basePath($item['screenshot']) ?>" alt="<?= sprintf($this->translate('Screenshot for %s theme'), $displayName) ?>" title="<?= sprintf($this->translate('Screenshot for %s theme'), $displayName) ?>" />
                <?php endif ?>

                <div class="theme-info">
                    <h3><?= $displayName ?></h3>

                    <?php if (isset($item['description'])): ?>

                    <p><?= $this->translate($item['description']) ?></p>
                    <?php endif ?>

                    <ul class="list-unstyled">
                    <?php if (in_array($name, $registeredThemes)): ?>
                        <?php if ($name !== $options->getFrontendThemeName()): ?>

                        <li><a href="<?= $this->url('sc-admin/layout/index', ['theme' => $name]) ?>"><?= $this->translate('Layout') ?></a></li>
                        <li><a href="<?= $this->url('sc-admin/theme/default', ['theme' => $name, 'side' => 'frontend']) ?>"><?= $this->translate('Set as frontend') ?></a></li>
                        <?php else: ?>

                        <li><a href="<?= $this->url('sc-admin/layout/index', ['theme' => $name]) ?>"><?= $this->translate('Lyout') ?></a></li>
                        <?php endif ?>
                        <?php if ($name !== $options->getBackendThemeName() && isset($item['provides_backend']) && $item['provides_backend']): ?>

                        <li><a href="<?= $this->url('sc-admin/theme/default', ['theme' => $name, 'side' => 'backend']) ?>"><?= $this->translate('Set as backend') ?></a></li>
                        <?php endif ?>
                        <?php if($name !== $options->getFrontendThemeName() && $name !== $options->getBackendThemeName()): ?>

                        <li><a href="<?= $this->url('sc-admin/theme/disable', ['theme' => $name]) ?>"><?= $this->translate('Disable') ?></a></li>
                        <?php endif ?>
                    <?php else: ?>

                        <li><a href="<?= $this->url('sc-admin/theme/enable', ['theme' => $name]) ?>"><?= $this->translate('Enable') ?></a></li>
                    <?php endif ?>

                    </ul>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
<?php endforeach ?>
