<?php
    $this->headTitle($this->translate('Configure Widget'));
    $this->headScript()->appendFile($this->basePath() . '/sc-default/js/stratch.js');
?>
<?php if (isset($messages)): ?>

    <?= $this->partial('sc-default/template/backend/partial/error.phtml') ?>

<?php endif ?>
<?php
    $form->prepare();
    echo $this->form()->openTag($form);
?>

    <div class="row">
        <div class="col-lg-12">
            <div class="form-group content-helper">
                <div class="btn-group">
                    <?= $this->formButton($form->get('save')) ?>

                </div>
                <a href="<?= $this->url('sc-admin/layout', ['theme' => $widget->getTheme()]) ?>" class="btn btn-default"><?= $this->translate('Lyout') ?></a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 col-lg-8">
            <div class="editor-tabs">
                <ul class="nav nav-tabs">
                    <li class="active"><a href="<?= $this->url('sc-admin/widget/configure', ['id' => $widget->getId()]) ?>"><span class="glyphicon glyphicon-cog"></span><?= $this->translate('Configure') ?></a></li>
                    <?php if(isset($config['backend'])): ?>

                    <li><a href="<?= $this->url('sc-admin/widget/edit', ['id' => $widget->getId()]) ?>"><span class="glyphicon glyphicon-edit"></span><?= $this->translate('Edit') ?></a></li>
                    <?php endif ?>

                    <li><a href="<?= $this->url('sc-admin/widget/visibility', ['widget_id' => $widget->getId()]) ?>"><span class="glyphicon glyphicon-list"></span><?= $this->translate('Visibility') ?></a></li>
                </ul>
            </div>
            <div class="under-tabs stratch">
                <div class="form-group">
                    <?= $this->formRow($form->get('display_name')) ?>

                </div>
                <div class="form-group">
                    <?= $this->formRow($form->get('description')) ?>

                </div>
                <div class="clearfix"></div>
            </div>
        </div>
        <div class="col-md-4 col-lg-4 indent-xs-sm">
            <div class="panel-group accordion" id="accordion">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#rolesOptions">
                                <?php echo $this->translate('Roles') ?>

                            </a>
                        </h4>
                    </div>
                    <div id="rolesOptions" class="panel-collapse collapse in">
                        <div class="panel-body">
                            <?= $this->formRow($form->get('roles')) ?>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?= $this->form()->closeTag($form) ?>
