<?php
    $this->headTitle($this->translate('Configure Widget'));
?>
<?php if (isset($messages)): ?>

    <?= $this->partial('sc-default/template/backend/partial/error.phtml') ?>

<?php endif ?>
<?php
    $form->prepare();
    echo $this->form()->openTag($form);
?>

    <div class="row">
        <div class="col-lg-12">
            <div class="form-group content-helper">
                <div class="btn-group">
                    <?= $this->formButton($form->get('save')) ?>

                </div>
                <a href="<?= $this->url('sc-admin/layout', ['theme' => $theme]) ?>" class="btn btn-default"><?= $this->translate('Lyout') ?></a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12 form-group">
            <ul class="nav nav-tabs">
                <li class="active"><a href="#">Configure</a></li>
                <li><a href="#">Edit</a></li>
            </ul>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-8 col-md-8 col-lg-8 panel">
            <div class="form-group">
                <?= $this->formRow($form->get('display_name')) ?>

            </div>
            <div class="form-group">
                <?= $this->formRow($form->get('description')) ?>

            </div>
        </div>
        <div class="col-sm-8 col-md-4 col-lg-4">
            <div class="outlined">
                <div class="form-group">
                    <?= $this->formRow($form->get('roles')) ?>

                </div>
            </div>
        </div>
    </div>
<?= $this->form()->closeTag($form) ?>
