
<div id="main">
    <h1><?= $this->translate('An error occurred') ?></h1>
    <h3><?= $this->message ?></h3>
    <div class="nav">
        <p>
            <a href="/">&rarr; <?= $this->translate("Home") ?></a> |
            <a href="javascript:window.history.back();">&larr; <?= $this->translate('Back') ?></a>
        </p>
    </div>

    <?php if (isset($this->display_exceptions) && $this->display_exceptions): ?>
        <?php if (isset($this->exception) && $this->exception instanceof Exception): ?>

        <div id="details">
            <hr/>
            <h3><?= $this->translate('Additional information') ?>:</h3>
            <h4><?= get_class($this->exception); ?></h4>
            <dl>
                <dt><?= $this->translate('File') ?>:</dt>
                <dd>
                    <pre class="prettyprint linenums"><?= $this->exception->getFile() ?>:<?= $this->exception->getLine() ?></pre>
                </dd>
                <dt><?= $this->translate('Message') ?>:</dt>
                <dd>
                    <pre class="prettyprint linenums"><?= $this->exception->getMessage() ?></pre>
                </dd>
                <dt><?= $this->translate('Stack trace') ?>:</dt>
                <dd>
                    <pre class="prettyprint linenums"><?= $this->exception->getTraceAsString() ?></pre>
                </dd>
            </dl>
            <?php
                $e = $this->exception->getPrevious();
                if ($e) :
            ?>
            <hr/>
            <h3><?= $this->translate('Previous exceptions') ?>:</h3>
            <ul class="unstyled">
                <?php while($e) : ?>
                <li>
                    <h4><?= get_class($e); ?></h4>
                    <dl>
                        <dt><?= $this->translate('File') ?>:</dt>
                        <dd>
                            <pre><?= $e->getFile() ?>:<?= $e->getLine() ?></pre>
                        </dd>
                        <dt><?= $this->translate('Message') ?>:</dt>
                        <dd>
                            <pre><?= $e->getMessage() ?></pre>
                        </dd>
                        <dt><?= $this->translate('Stack trace') ?>:</dt>
                        <dd>
                            <pre><?= $e->getTraceAsString() ?></pre>
                        </dd>
                    </dl>
                </li>
                <?php
                    $e = $e->getPrevious();
                    endwhile;
                ?>
            </ul>
        </div>
        <?php endif ?>

    <?php else: ?>

    <h4><?= $this->translate('No Exception available') ?></h4>

    <?php endif ?>

    <?php endif ?>

</div>
