<?php
    if (isset($title)) {
        $this->headTitle($this->translate($title));
    }
?>

<div id="header">
    <?php if (isset($brand)): ?>

    <div class="brand"><?= $brand  ?></div>
    <?php endif ?>

    <h3>
    <?php if (isset($step) && false !== $step): ?>

    <span class = "step"><?= $this->translate('Step') ?> <?= $this->translate($step) ?>.</span>
    <?php endif ?>

    <?php if (isset($header)): ?>

        <?= $this->translate($header) ?>

    <?php endif ?>

    </h3>
</div>
<div id="main">
<?php if (isset($errors)): ?>

    <h4 id="errors"><?= $this->translate('Installation error:') ?></h4>
    <p>
        <?php if (is_array($errors)): ?>

            <?php if (isset($errors['table'])): ?>

            <table>
                <?php if (isset($errors['table']['head'])): ?>

                <tr>
                    <?php foreach ($errors['table']['head'] as $th): ?>

                    <th><?= $this->translate($th) ?></th>
                    <?php endforeach ?>

                </tr>
                <?php endif ?>
                <?php foreach ($errors['table']['body'] as $tr): ?>

                    <tr>
                        <?php foreach ($tr as $td): ?>

                        <td><?= $this->translate($td) ?></td>
                        <?php endforeach ?>

                    </tr>
                <?php endforeach ?>

            </table>
            <?php else: ?>
                <?php foreach($errors as $error): ?>

                <?= $this->translate($error) ?><br/>

                <?php endforeach ?>
            <?php endif ?>
        <?php else: ?>

            <?= $this->translate($errors) ?>
        <?php endif ?>

    </p>

<?php elseif (isset($info)): ?>

    <p><?= $this->translate($info) ?></p>
<?php endif ?>
</div>
<div id="footer">
    <?php if (isset($form)): ?>
    <?php
    $form->setAttribute('action', $this->url('sc-install', ['process' => 'process']));
    $form->prepare();
    echo
        $this->form()->openTag($form),
        $this->formCollection($form),
        $this->form()->closeTag($form);
    ?>
    <?php else: ?>

        <a href="<?= $this->url('sc-install', array('process' => 'process')) ?>" class="btn-primary"><?= $this->translate('Continue') ?></a>
    <?php endif ?>

</div>
