<?php $this->headTitle($this->translate('Add Files')) ?>
<?php
    $form->prepare();
    echo $this->form()->openTag($form);
?>

    <div class="row">
        <div class="col-lg-12">
            <div class="form-group content-helper">
                <?= $this->formButton($form->get('upload')) ?>

                <a href="<?= $this->url('sc-admin/content-manager') ?>" class="btn btn-default"><?= $this->translate('Manager') ?></a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <?= $this->formLabel($form->get('file')) ?>
            <?= $this->formFile($form->get('file')) ?>
            <?php if(count($form->get('file')->getMessages())): ?>

            <div class="alert alert-warning pull-left"><?= $this->formElementErrors($form->get('file')) ?></div><div class="clearfix"></div>

            <?php endif ?>

            <p class="help-block"><?= $this->translate('File names can only consist of letters of the alphabet, spaces, hyphens, and underscores.') ?><br /><?= sprintf($this->translate('Maximum upload file size: %s MB.'), '2') ?></p>
        </div>
    </div>
    <?= $this->form()->closeTag($form) ?>
