<?php $this->headTitle($this->translate('Edit Files')) ?>
<?php
    $form->prepare();
    echo $this->form()->openTag($form);
?>

    <div class="row">
        <div class="col-lg-12">
            <div class="form-group content-helper">
                <?php echo $this->formButton($form->get('save')) ?>

                <a href="<?php echo $this->url('sc-admin/content-manager') ?>" class="btn btn-default"><?php echo $this->translate('Manager') ?></a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel-group accordion" id="accordion">

                <?php foreach($files = $form->get('files')->getIterator() as $i => $fieldset): ?>

                <?php $item = $fieldset->getObject() ?>

                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a class="accordion-toggle"<?php if(count($files) > 1): ?> data-toggle="collapse" data-parent="#accordion" href="#panel-<?php echo $i ?>"<?php endif ?>>
                                <?php echo $this->scContentFormat()->getIconPath($item) ?><span class="content-type"><?php echo $this->scContentFormat()->getExtension($item) ?></span>
                                <?php if(count($fieldset->get('title')->getMessages())): ?>

                                <span class="glyphicon glyphicon-warning-sign"></span>
                                <?php endif ?>

                                <span class="file-header"><?php echo $item->getTitle() ?></span>
                            </a>
                        </h4>
                    </div>
                    <div id="panel-<?php echo $i ?>" class="panel-collapse collapse<?php if($i == count($files) - 1): ?> in<?php endif ?>">
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-sm-8 col-md-8 col-lg-8">
                                    <div class="form-group">
                                        <?php echo $this->formText($fieldset->get('title')) ?>
                                        <?php if(count($fieldset->get('title')->getMessages())): ?>

                                        <div class="alert alert-warning"><?php echo $this->formElementErrors($fieldset->get('title')) ?></div>

                                        <?php endif ?>

                                    </div>
                                    <?php if($this->scContentFormat()->isWebImage($item)): ?>

                                        <div class="form-group"><?php echo $this->formRow($fieldset->get('content'))?></div>
                                    <?php endif ?>

                                    <div class="form-group">
                                        <?php echo $this->formRow($fieldset->get('description')) ?>

                                    </div>
                                </div>
                                <div class="col-sm-4 col-md-4 col-lg-4">
                                    <div class="outlined">
                                        <?php if($this->scContentFormat()->isWebImage($item)): ?>

                                            <div class="file-image-wrap"><?php echo $this->scContentFormat()->getIconPath($item) ?></div>
                                        <?php endif ?>

                                        <div class="file-info-wrap">
                                        <?php echo $this->partial('sc-default/template/backend/partial/content-info.phtml', array(
                                            'content' => $item,
                                            'meta' => $item->getInfo(),
                                        )) ?>

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <?php endforeach ?>

            </div>
        </div>
    </div>
    <?php echo $this->form()->closeTag($form) ?>
