<?php
    $this->headTitle($this->translate('Edit Layout'));
?>
<?php if (isset($messages)): ?>

    <?= $this->partial('sc-default/template/backend/partial/error.phtml') ?>
<?php endif ?>

<form action="<?= $this->url('sc-admin/layout', ['theme' => $theme->getName()]) ?>" method="post">
    <div class="row">
        <div class="col-lg-12">
            <div class="form-group content-helper">
                <div class="btn-group">
                    <button type="submit" class="btn btn-primary"><?= $this->translate('Save') ?></button>
                </div>
                <a href="<?= $this->url('sc-admin/themes') ?>" class="btn btn-default"><?= $this->translate('Themes') ?></a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <h3><?= $this->translate($theme->getDisplayName()) ?></h3>
            <?php if ($theme->getDescription()): ?>

            <p><?= $this->translate($theme->getDescription()) ?></p>
            <?php endif ?>

        </div>
    </div>
    <div class="row">
        <div class="col-sm-8 col-md-8 col-lg-8">
            <div class="panel-group accordion" id="accordion">
                <?php $first = true ?>
                <?php foreach ($regions as $regionName => $widgets): ?>

                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#describe-<?= $regionName ?>">
                                <?= $this->translate($regions->getDisplayName($regionName)) ?>

                            </a>
                        </h4>
                    </div>
                    <div id="describe-<?= $regionName ?>" class="panel-collapse collapse<?php if($first): ?> in<?php $first = false; endif; ?>">
                        <div class="panel-body">
                        <?php if ($widgets->isEmpty()): ?>

                            <em><?= $this->translate('No widgets in this region') ?></em>
                        <?php endif ?>
                        <?php foreach ($widgets as $widget): ?>

                        <div class="row form-group">
                            <div class="col-sm-4 form-group-item">
                                <h4><?= $this->translate($widget->getDisplayName()) ?></h4>
                                <?php if ($widget->hasDescription()): ?>

                                <?= $widget->getDescription() ?>
                                <?php endif ?>

                            </div>
                            <div class="col-sm-2 form-group-item layout-actions">
                                <?php if (! $widget->findOption('immutable')): ?>

                                <a href="<?= $this->url('sc-admin/widget/configure', ['id' => $widget->getId()]) ?>">Configure</a>
                                <?php endif ?>

                            </div>
                            <div class="col-sm-2 form-group-item">
                                <input type="text" name="position[<?= $widget->getId() ?>]" class="form-control input-sm" maxlength="3" value="<?= $widget->getPosition() ?>" />
                                <input type="hidden" name="old_position[<?= $widget->getId() ?>]" value="<?= $widget->getPosition() ?>" />
                            </div>
                            <div class="col-sm-4 form-group-item">
                                <select name="region[<?= $widget->getId() ?>]" class="form-control input-sm">
                                    <?php foreach ($regions->getNames() as $itemRegionName => $itemRegionDisplayName): ?>

                                    <option value="<?= $itemRegionName?>"<?php if ($itemRegionName == $regionName): ?> selected="selected"<?php endif ?>><?= $this->translate($itemRegionDisplayName) ?></option>
                                    <?php endforeach ?>

                                </select>
                                <input type="hidden" name="old_region[<?= $widget->getId() ?>]" value="<?= $regionName ?>" />
                            </div>
                        </div>
                        <?php endforeach ?>

                        </div>
                    </div>
                </div>
                <?php endforeach ?>

            </div>
        </div>
    </div>
</form>
