<?= $this->doctype(); ?>

<html lang="en">
<head>
<meta charset="utf-8">
<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/sc-default/img/favicon.ico'))
                ->appendStylesheet($this->basePath() . '/sc-default/css/bootstrap.min.css')
                ->appendStylesheet($this->basePath() . '/sc-default/css/bootstrap-theme.min.css')
                ->appendStylesheet($this->basePath() . '/sc-default/css/error.css')
?>

</head>
<body>
<div class="content">
    <div class="row">
        <div class="col-lg-12">
            <?= $this->content ?>
        </div>
    </div>
</div>
</body>
