<?php echo $this->doctype(); ?>

<html lang="en">
<head>
<meta charset="utf-8">
<?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')
                            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')

?>

<!-- Styles -->
<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/sc-default/img/favicon.ico'))
                ->appendStylesheet($this->basePath() . '/sc-default/css/bootstrap.min.css')
                ->appendStylesheet($this->basePath() . '/sc-default/css/common.css')
?>

<!-- Scripts -->
<?php echo $this->headScript()->appendFile($this->basePath() . '/sc-default/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                              ->appendFile($this->basePath() . '/sc-default/js/jquery.min.js')
                              ->appendFile($this->basePath() . '/sc-default/js/bootstrap.min.js')
                              ->appendFile($this->basePath() . '/sc-default/js/respond.min.js')
?>
    
</head>
<body>
<h1>FRONTEND</h1>

<?php 
    foreach($registry as $region => $widgets){
        foreach($widgets as $widget) {
            echo $this->$widget;
        }
    }
?>
<?php echo $this->content ?>
</body>
</html>
