
    </div><!-- row #middle -->
    </div><!-- container -->
</div><!-- top -->
<footer id="footer">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <?php foreach($widgets as $widget): ?>
                    <?php $widgetName = $widget->getName() ?>

                    <?= $this->layout()->$widgetName ?>
                <?php endforeach ?>

            </div>
        </div>
    </div>
</footer>
