<div id="top">
    <header id="header">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <?php foreach($widgets as $widget): ?>
                        <?php $widgetId = $widget->getId() ?>

                        <?= $this->layout()->$widgetId ?>
                    <?php endforeach ?>

                </div>
            </div>
        </div>
    </header>
    <div class="container">
    <div id="middle" class="row">
