<?php $this->headStyle()->captureStart() ?>
html, body {
    min-height:100%;
}
body {
    padding:20px 6px 40px;
    text-align:center;
    background: #eff2f4; /* Old browsers */
/* IE9 SVG, needs conditional override of 'filter' to 'none' */
background: url(data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiA/Pgo8c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgdmlld0JveD0iMCAwIDEgMSIgcHJlc2VydmVBc3BlY3RSYXRpbz0ibm9uZSI+CiAgPGxpbmVhckdyYWRpZW50IGlkPSJncmFkLXVjZ2ctZ2VuZXJhdGVkIiBncmFkaWVudFVuaXRzPSJ1c2VyU3BhY2VPblVzZSIgeDE9IjAlIiB5MT0iMCUiIHgyPSIwJSIgeTI9IjEwMCUiPgogICAgPHN0b3Agb2Zmc2V0PSIwJSIgc3RvcC1jb2xvcj0iI2VmZjJmNCIgc3RvcC1vcGFjaXR5PSIxIi8+CiAgICA8c3RvcCBvZmZzZXQ9IjEwMCUiIHN0b3AtY29sb3I9IiNmZmZmZmYiIHN0b3Atb3BhY2l0eT0iMSIvPgogIDwvbGluZWFyR3JhZGllbnQ+CiAgPHJlY3QgeD0iMCIgeT0iMCIgd2lkdGg9IjEiIGhlaWdodD0iMSIgZmlsbD0idXJsKCNncmFkLXVjZ2ctZ2VuZXJhdGVkKSIgLz4KPC9zdmc+);
background: -moz-linear-gradient(top,  #eff2f4 0%, #ffffff 100%); /* FF3.6+ */
background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#eff2f4), color-stop(100%,#ffffff)); /* Chrome,Safari4+ */
background: -webkit-linear-gradient(top,  #eff2f4 0%,#ffffff 100%); /* Chrome10+,Safari5.1+ */
background: -o-linear-gradient(top,  #eff2f4 0%,#ffffff 100%); /* Opera 11.10+ */
background: -ms-linear-gradient(top,  #eff2f4 0%,#ffffff 100%); /* IE10+ */
background: linear-gradient(to bottom,  #eff2f4 0%,#ffffff 100%); /* W3C */
filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#eff2f4', endColorstr='#ffffff',GradientType=0 ); /* IE6-8 */

    color:#222222;
}
h1, h2, h3, h4, h5, h6 {
    margin:0;
    font-family:inherit;
    font-weight:500;
    color:626262;
}
h1 {
    font-size:36px;
}
h2 {
    font-size:30px;
}
h3 {
    font-size:24px;
}
h4 {
    font-size:18px;
}
h5 {
    font-size:14px;
}
h6 {
    font-size:12px;
}
p {
    margin:0;
}
form {
    padding:12px 20px;
    text-align:left;
}
label {
    margin:5px 0;
    font-weight:600;
    display:block;
    color:555555;
}
input, select, textarea {
    margin:5px 0;
    font-family:inherit;
    font-size:14px;
    line-height:inherit;
}
select, textarea, input[type="text"], input[type="password"],
input[type="number"], input[type="email"], input[type="url"],
input[type="search"], input[type="tel"], input[type="color"] {
    display: block;
    width: 100%;
    height:34px;
    padding:6px 12px;
    color:#555555;
    vertical-align:middle;
    background-color:#ffffff;
    border:1px solid #cccccc;
    border-radius:4px;
    -webkit-box-sizing:border-box;
       -moz-box-sizing:border-box;
            box-sizing:border-box;
    -webkit-box-shadow:inset 0 1px 1px rgba(0, 0, 0, 0.075);
            box-shadow:inset 0 1px 1px rgba(0, 0, 0, 0.075);
    -webkit-transition:border-color ease-in-out 0.15s, box-shadow ease-in-out 0.15s;
            transition:border-color ease-in-out 0.15s, box-shadow ease-in-out 0.15s;
}
select:focus, textarea:focus, input[type="text"]:focus, input[type="password"]:focus,
input[type="number"]:focus, input[type="email"]:focus, input[type="url"]:focus,
input[type="search"]:focus, input[type="tel"]:focus, input[type="color"]:focus {
    border-color:#66afe9;
    outline:0;
    -webkit-box-shadow:0 0 8px rgba(102, 175, 233, 0.6);
            box-shadow:0 0 8px rgba(102, 175, 233, 0.6);
}
select {
    height:36px;
    padding:8px 12px;
}
code {
    padding:2px 4px;
    font-size:90%;
    font-family:Monaco, Menlo, Consolas, "Courier New", monospace;
    white-space:nowrap;
    background-color:#f6f6f6;
    border:1px solid #eee;
    -webkit-border-radius:4px;
       -moz-border-radius:4px;
            border-radius:4px;
    color:#005892;
}
table {
    width:100%;
    margin:16px 0 0;
    border-collapse:collapse;
}
th, td {
    padding:6px;
    font-size:95%;
    text-align:left;
    vertical-align:top;
    word-wrap:break-word;
    border:1px solid #e1e2e3ddd;
}
.brand img {
    max-height:24px;
    margin-left:-4px;
}
.btn-primary {
    min-width:50px;
    margin:6px auto;
    padding:8px 14px;
    font-size:14px;
    font-weight:400;
    text-align:center;
    text-decoration:none;
    vertical-align:middle;
    background-color:#428bca;
    border: 1px solid #357ebd;
    border-radius:4px;
    display:inline-block;
    color:#ffffff;
    text-shadow:0 -1px 0 rgba(0,0,0,0.2);
    -webkit-box-shadow:inset 0 1px 0 rgba(255,255,255,0.15), 0 1px 1px rgba(0,0,0,0.075);
	    box-shadow:inset 0 1px 0 rgba(255,255,255,0.15), 0 1px 1px rgba(0,0,0,0.075);
    background-image: -webkit-gradient(linear, left 0, left 100%, from(#428bca), to(#3071a9));
    background-image: -webkit-linear-gradient(top, #428bca, 0%, #3071a9, 100%);
    background-image: -moz-linear-gradient(top, #428bca 0, #3071a9 100%);
    background-image: linear-gradient(to bottom, #428bca 0, #3071a9 100%);
    background-repeat: repeat-x;
    cursor:pointer;
}
.btn-primary:hover,
.btn-primary:focus,
.btn-primary:active {
    color:#ffffff;
    background-color:#3071a9;
    border-color: #2d6ca2;
    filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#ff428bca', endColorstr='#ff3071a9', GradientType=0);

}
#wrap {
    max-width:600px;
    min-width:270px;
    margin:0 auto;
    font-size:16px;
    font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
    line-height:1.428;
    -webkit-border-radius:6px;
       -moz-border-radius:6px;
            border-radius:6px;
    -webkit-box-shadow:0 1px 4px rgba(0,0,0,0.05);
            box-shadow:0 1px 4px rgba(0,0,0,0.05);
    border:1px solid #e1e2e3;
    background:#fff;
}
#header, #main, #footer {
    margin:0;
}
#header {
    min-height:40px;
    padding:22px 14px 10px;
    border-bottom:1px solid #e1e2e3;
    -webkit-border-radius:6px 6px 0 0;
       -moz-border-radius:6px 6px 0 0;
            border-radius:6px 6px 0 0;
    -webkit-box-shadow:0 3px 4px rgba(0,0,0,0.05);
            box-shadow:0 3px 4px rgba(0,0,0,0.05);
    background:#f8f8f8;
    background-image:-webkit-gradient(linear, left 0, left 100%, from(#fff), to(#f8f8f8));
    background-image:-webkit-linear-gradient(top, #fff, 0%, #f8f8f8, 100%);
    background-image:-moz-linear-gradient(top, #fff 0, #f8f8f8 100%);
    background-image:linear-gradient(to bottom, #fff 0, #f8f8f8 100%);
    background-repeat:repeat-x;
}
#header h1, #header h2, #header h3, #header h4, #header h5, #header h6 {
    font-size:18px;
    font-weight:400;
}
#errors {
    color:#c7254e;
}
#main {
    padding:24px 24px 32px;
    border-bottom:1px solid #e1e2e3;
}
#footer {
    padding:6px 16px;
    background:#f8f8f8;
    -webkit-border-radius:0 0 6px 6px;
       -moz-border-radius:0 0 6px 6px;
            border-radius:0 0 6px 6px;
}
<?php $this->headStyle()->captureEnd() ?>
<?php echo $this->doctype(); ?>

<html lang="<?= \Locale::getPrimaryLanguage(\Locale::getDefault()) ?>">
<head>
<meta charset="utf-8">
<?php echo $this->headStyle() ?>

<?php echo $this->headTitle($this->translate($title), \Zend\View\Helper\Placeholder\Container\AbstractContainer::PREPEND)->setSeparator(' . ')->setAutoEscape(false) ?>

</head>

<body>
<div id="wrap">
    <?php echo $this->content ?>

</div>
</body>